site_name: PyTorch-LifeStream
nav:
    - Welcome: index.md
    - 'User Guide':
        - 'Sequential Data':
            - 'Sequential Data Definition': 'sequential_data_definition.md'
            - 'Feature naming': 'feature_naming.md'
        - 'Training Methods': 'methods.md'
        - 'How to guide':
            - 'Data preparation': '#'
            - 'Sequential model creation': '#'
            - 'Frameworks usage': '#'
            - 'Encoder training': '#'
            - 'Inference': '#'

        - 'ptls':
            - 'ptls.data_load':
                - 'padded batch': 'data_load/padded_batch.md'
                - 'datasets': 'data_load/datasets.md'
            - 'ptls.nn':
                - 'trx_encoder': 'nn/trx_encoder.md'
                - 'seq_encoder': 'nn/seq_encoder.md'
                - 'head': 'nn/head.md'
                - 'pb': 'nn/pb.md'
            - 'ptls.frames':
                - 'common usage pattern': 'frames/common_usage.md'
                - 'coles': 'frames/coles.md'
                - 'cpc': 'frames/cpc.md'
                - 'bert': 'frames/bert.md'
                - 'supervised': 'frames/supervised.md'
                - 'inference': 'frames/inference.md'

theme: readthedocs
